[build]
  base = "app/"
  publish = "app/build/"
  command = "npm run build"

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 