[build]
  base = "app/"
  publish = "build/"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Ensure this plugin is present to install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Proxy rule: All requests to /api/* on Netlify will be forwarded to Render
[[redirects]]
  from = "/api/*"
  to = "https://fitvice-oad4.onrender.com/:splat"
  status = 200 # Important: Use 200 for proxying
  force = true # Ensure this rule takes precedence

# This rule is likely no longer needed if api.js is just serving the backend routes
# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/api/:splat"
#   status = 200

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  CI = "false"
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7" 