[build]
  command = "npm run build"
  publish = "build"
  base = "app"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  CI = "false"

[functions]
  included_files = [
    "netlify/functions/node_modules/**/*",
    "netlify/functions/*.js",
    "netlify/functions/package.json"
  ]
  node_bundler = "esbuild"
  external_node_modules = ["aws-sdk"]
  node_bundler_flags = "--minify --tree-shaking=true" 